# straight up lifted from
# https://github.com/AlexNabokikh/nix-config/blob/master/home/modules/darwin-aerospace.nix
# Start AeroSpace at login
start-at-login = true

# Normalization settings
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion layout settings
accordion-padding = 30

# Default root container settings
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus settings
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = ['move-mouse window-lazy-center'] # problem is it even moves the cursor on tooltips

# Automatically unhide macOS hidden apps
automatically-unhide-macos-hidden-apps = true

# main is LG C3 via HDMI2.1; built-in = Macbook display
[workspace-to-monitor-force-assignment]
1 = 'main' # kitty
2 = 'built-in' # firefox
3 = 'main' # safari/firefox
4 = 'main' # messages,discord
5 = 'built-in' # finder
6 = 'built-in' # activity monitor, system settings
7 = 'main' # spotify/applemusic
8 = 'main'
9 = 'main'
0 = 'main'

# Key mapping preset
[key-mapping]
preset = 'qwerty'

# Gaps settings
[gaps]
inner.horizontal = 13
inner.vertical =   13
outer.left =       13
outer.bottom =     13
outer.top =        13
outer.right =      13

# Main mode bindings
[mode.main.binding]
# Launch applications
alt-shift-enter = 'exec-and-forget open -na kitty' # -na is [n]ew instance of [a]pplication
alt-shift-b = 'exec-and-forget open -a firefox'
alt-shift-m = 'exec-and-forget open -a Messages'
alt-shift-e = 'exec-and-forget open -na kitty --args yazi' # immediately opens yazi in a new kitty terminal

# Window management
alt-q = "close"
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
cmd-shift-f = 'fullscreen'

# Focus movement
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window movement
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize windows
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Navigate to workspace
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

# Move windows to workspaces
cmd-alt-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-alt-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-alt-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-alt-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-alt-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-alt-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-alt-7 = ['move-node-to-workspace 7', 'workspace 7']
cmd-alt-8 = ['move-node-to-workspace 8', 'workspace 8']
cmd-alt-9 = ['move-node-to-workspace 9', 'workspace 9']

# Workspace navigation
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Enter service mode
cmd-alt-semicolon = 'mode service'

# Service mode bindings
[mode.service.binding]
# Reload config and exit service mode
esc = ['reload-config', 'mode main']

# Reset layout
r = ['flatten-workspace-tree', 'mode main']

# Toggle floating/tiling layout
f = ['layout floating tiling', 'mode main']

# Close all windows but current
backspace = ['close-all-windows-but-current', 'mode main']

# Join with adjacent windows
alt-ctrl-h = ['join-with left', 'mode main']
alt-ctrl-j = ['join-with down', 'mode main']
alt-ctrl-k = ['join-with up', 'mode main']
alt-ctrl-l = ['join-with right', 'mode main']

# Window detection rules
# [[on-window-detected]]
# if.app-id = 'net.kovidgoyal.kitty'
# run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout tiling', 'move-node-to-workspace 6']
