# straight up lifted from
#l https://github.com/AlexNabokikh/nix-config/blob/master/home/modules/darwin-aerospace.nix
# Start AeroSpace at login
start-at-login = true

# Normalization settings
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion layout settings
accordion-padding = 30

# Default root container settings
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus settings
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = ['move-mouse window-lazy-center'] # problem is it even moves the cursor on tooltips

# Automatically unhide macOS hidden apps
automatically-unhide-macos-hidden-apps = true

# Key mapping preset
[key-mapping]
preset = 'qwerty'

# Gaps settings
[gaps]
inner.horizontal = 13
inner.vertical =   13
outer.left =       13
outer.bottom =     13
outer.top =        13
outer.right =      13

# Main mode bindings
[mode.main.binding]
# Launch applications
alt-shift-enter = 'exec-and-forget open -na kitty'
alt-shift-b = 'exec-and-forget open -a firefox'
alt-shift-t = 'exec-and-forget open -a "Telegram"'
alt-shift-f = 'exec-and-forget open -a Finder'

# Window management
alt-q = "close"
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-m = 'fullscreen'

# Focus movement
cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'
# alt-h = 'focus left'
# alt-j = 'focus down'
# alt-k = 'focus up'
# alt-l = 'focus right'

# Window movement
cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

# Resize windows
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Workspace management
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
# alt-7 = 'workspace 7'
# alt-8 = 'workspace 8'
# alt-9 = 'workspace 9'

# Move windows to workspaces
cmd-alt-1 = 'move-node-to-workspace 1'
cmd-alt-2 = 'move-node-to-workspace 2'
cmd-alt-3 = 'move-node-to-workspace 3'
cmd-alt-4 = 'move-node-to-workspace 4'
cmd-alt-5 = 'move-node-to-workspace 5'
cmd-alt-6 = 'move-node-to-workspace 6'
# alt-shift-7 = 'move-node-to-workspace 7'
# alt-shift-8 = 'move-node-to-workspace 8'
# alt-shift-9 = 'move-node-to-workspace 9'

# Workspace navigation
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Enter service mode
alt-shift-semicolon = 'mode service'

# Service mode bindings
[mode.service.binding]
# Reload config and exit service mode
esc = ['reload-config', 'mode main']

# Reset layout
r = ['flatten-workspace-tree', 'mode main']

# Toggle floating/tiling layout
f = ['layout floating tiling', 'mode main']

# Close all windows but current
backspace = ['close-all-windows-but-current', 'mode main']

# Join with adjacent windows
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Window detection rules
[[on-window-detected]]
if.app-id = 'com.firefox.Browser'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'org.kitty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.obsproject.obs-studio'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = 'move-node-to-workspace 5'
